# Generated by Django 5.2.10 on 2026-01-13 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('currency', models.CharField(default='usd', max_length=16)),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('external_price_id', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=32)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='usd', max_length=16)),
                ('provider', models.CharField(blank=True, default='manual', max_length=64)),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.student')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=32)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('allowed_semester_numbers', models.JSONField(blank=True, null=True)),
                ('external_subscription_id', models.CharField(blank=True, default='', max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(max_length=64)),
                ('event_id', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField()),
            ],
            options={
                'unique_together': {('provider', 'event_id')},
            },
        ),
    ]
