# Generated by Django 5.2.10 on 2026-01-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='materials_limit',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of materials that can be processed (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='semesters_limit',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of semesters that can be parsed (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tests_limit',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of tests that can be solved (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='materials_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='semesters_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='tests_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
