# Generated by Django 5.2.10 on 2026-01-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_plan_materials_limit_plan_semesters_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='courses_limit',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of courses/lessons (e.g. Philosophy, Math) that can be processed (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='courses_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
