# Generated by Django 5.2.10 on 2026-01-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_plan_courses_limit_subscription_courses_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='courses_enabled',
            field=models.BooleanField(default=True, help_text='Allow processing courses/lessons in this plan'),
        ),
        migrations.AddField(
            model_name='plan',
            name='materials_enabled',
            field=models.BooleanField(default=True, help_text='Allow processing materials in this plan'),
        ),
        migrations.AddField(
            model_name='plan',
            name='semesters_enabled',
            field=models.BooleanField(default=True, help_text='Allow parsing semesters in this plan'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tests_enabled',
            field=models.BooleanField(default=True, help_text='Allow solving tests in this plan'),
        ),
    ]
