# Generated by Django 5.2.10 on 2026-01-13 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=2000)),
                ('control_type', models.CharField(blank=True, default='', max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('type', models.CharField(blank=True, default='material', max_length=64)),
                ('is_blocked', models.BooleanField(default=False)),
                ('data_index', models.CharField(blank=True, default='', max_length=128)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.JSONField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='synergy.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='SynergyCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('login', models.CharField(max_length=255)),
                ('password_encrypted', models.TextField(blank=True, default='')),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='synergy_credential', to='accounts.student')),
            ],
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['student', 'semester_number'], name='synergy_cou_student_8478aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('student', 'url')},
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['student', 'type'], name='synergy_mat_student_5e6fe3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('student', 'number')},
        ),
    ]
