# Generated by Django 5.2.10 on 2026-01-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='blocked_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='material',
            name='raw',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='section_path',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
