# Generated by Django 5.2.10 on 2026-01-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
            ],
            options={
                'indexes': [models.Index(fields=['external_id'], name='accounts_st_externa_3ba1c0_idx'), models.Index(fields=['email'], name='accounts_st_email_ab97ee_idx')],
            },
        ),
    ]
