# Generated by Django 5.2.10 on 2026-01-13 06:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('login', 'Login'), ('sync_semesters', 'Sync semesters'), ('sync_courses', 'Sync courses'), ('sync_materials', 'Sync materials'), ('process_material', 'Process material'), ('solve_test', 'Solve test')], max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('error', models.TextField(blank=True, default='')),
                ('params', models.JSONField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'status'], name='jobs_job_student_99763a_idx'), models.Index(fields=['type', 'status'], name='jobs_job_type_aec67a_idx')],
            },
        ),
    ]
