# Generated by Django 5.2.10 on 2026-01-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('login', 'Login'), ('sync_semesters', 'Sync semesters'), ('sync_courses', 'Sync courses'), ('sync_materials', 'Sync materials'), ('sync_full', 'Sync full (semesters/courses/materials)'), ('sync_semester_full', 'Sync single semester (courses + materials)'), ('sync_all_parallel', 'Sync all semesters in parallel'), ('process_material', 'Process material'), ('solve_test', 'Solve test')], max_length=64),
        ),
    ]
